---
# Playbook to install proxy and its repositories
# before going ahead with another tasks in the bastion hostname
- block:
  - name: Remove comment for baseurl in repos
    replace:
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: '^#baseurl'
      replace: 'baseurl'
    loop: "{{ repo_names }}"
  - name: comment out mirrorlist in repo
    replace:
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: '(^mirrorlist.*)'
      replace: '#\1'
    loop: "{{ repo_names }}"
  - name: comment out metalink in repo
    replace:
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: '(^metalink.*)'
      replace: '#\1'
    loop: "{{ repo_names }}"
  become: true
  when:
    - repo_names is defined
    - repo_names | length > 0

- name: configure proxy for yum repositories
  become: true
  lineinfile:
    path: /etc/yum.conf
    regexp: '^proxy='
    line: "proxy={{ proxy }}"
    state: present
