- hosts: localhost
  gather_facts: no

  vars_files:
  - metadata.json

  tasks:
  - name: 'Compute CiscoACI resource names'
    set_fact:
      os_network2: "{{ infraID }}-network2"
      os_subnet2: "{{ infraID }}-nodes2"
      os_port_bootstrap2: "{{ infraID }}-bootstrap-port2"
      os_port_master2: "{{ infraID }}-master-port2"
      os_port_worker2: "{{ infraID }}-worker-port2
