- import_tasks: common.yaml

- name: 'Create a subnet'
  os_subnet:
    name: "{{ os_subnet }}11"
    network_name: "{{ os_network }}"
    cidr: "{{ os_subnet_range }}"
    allocation_pool_start: "{{ os_subnet_range | next_nth_usable(10) }}"
    allocation_pool_end: "{{ os_subnet_range | ipaddr('last_usable') }}"
  when: os_networking_type != "CiscoACI"
