# ingress_controller:
#   node_selector: String, must not be empty
#   tolerations_key: the key specified in the node taint
ingress_controller:
  node_selector: 'node-role.kubernetes.io/router: ""'
  tolerations_key: router
  api_cert:
    enable: false
    hostname: api.xyz.redacted.bgn
    secretname: api-tls-cert
    namespace: openshift-config
  apps_cert:
    enable: false
    secretname: apps-tls-cert
    namespace: openshift-ingress
  redactedca_cert:
    enable: false
    configmapname: redacted-ca
    namespace: openshift-config
