- name: ensure operator group for cluster logging exists
  k8s:
    kubeconfig: "{{ postinstall_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: "{{ clo_cluster_logging_operator_name }}"
        namespace: "{{ clo_cluster_logging_operator_namespace }}"
      spec:
        targetNamespaces:
        - "{{ clo_cluster_logging_operator_namespace }}"


- name: ensure subscription for cluster logging operator exists
  k8s:
    kubeconfig: "{{ postinstall_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ clo_cluster_logging_operator_name }}"
        namespace: "{{ clo_cluster_logging_operator_namespace }}"
      spec:
        channel: "{{ clo_cluster_logging_operator_channel }}"
        installPlanApproval: "Automatic"
        source: "redhat-operators"
        sourceNamespace: "openshift-marketplace"
        name: "{{ clo_cluster_logging_operator_name }}"