- name: ensure cluster monitoring config map exists
  k8s:
    kubeconfig: "{{ postinstall_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'cluster_monitoring_configmap.yml.j2')}}"

- name: Install Kube-Ops-View
  k8s:
    kubeconfig: "{{ postinstall_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'kube-ops-view-namespace.yml.j2')}}"

- name: Apply anyuid policy to kubeview
  shell: oc --config={{ postinstall_kubeconfig }} adm policy add-scc-to-user anyuid -z default -n {{ kubeview.namespace }} 

- name: Install Kube-Ops-View
  k8s:
    kubeconfig: "{{ postinstall_kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'kube-ops-view.yml.j2')}}"
