
# image_registry:
#   node_selector: String, must not be empty
#   tolerations_key: the key specified in the node taint
image_registry:
  node_selector: "node-role.kubernetes.io/infra: ''"
  tolerations_key: infra